version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    dotnet restore src/HomeAutio.Mqtt.TiVo.sln

    dotnet publish -c Release src/HomeAutio.Mqtt.TiVo.sln
artifacts:
- path: src\HomeAutio.Mqtt.TiVo\bin\$(configuration)\net5.0\publish
  name: HomeAutio.Mqtt.TiVo-$(appveyor_build_version)
deploy:
- provider: GitHub
  auth_token: $(GITHUB_API_KEY)
  artifact: src\HomeAutio.Mqtt.TiVo\bin\$(configuration)\net5.0\HomeAutio.Mqtt.TiVo-$(appveyor_build_version).zip